//! Williams System 11 sound board (the "XS").
//!
//! It is a whole computer separate from the game's: its own 6808 at 1 MHz, its
//! own RAM, its own banked ROM and its own PIA. The main board does not send it
//! audio: it sends it a **sound number** through an eight-bit latch plus a
//! handshake pulse, and this board takes care of the rest.
//!
//! # Memory map
//!
//! | Range | What's there |
//! |-------|---------|
//! | `$0000`-`$0FFF` | RAM |
//! | `$1000` | Bank select (write only) |
//! | `$2000`-`$2003` | PIA |
//! | `$8000`-`$BFFF` | Banked ROM window |
//! | `$C000`-`$FFFF` | Banked ROM window |
//!
//! The two 32 KB images do not fit together in the map, so they are seen 16 KB
//! at a time per window and the byte at `$1000` picks which half of each one.
//!
//! # PIA wiring (`wmssnd.c:516-527`)
//!
//! - **PA (input):** the sound latch the main board wrote.
//! - **PB (output):** the DAC.
//! - **CA1 (input):** the sound handshake.
//! - **CB1 (input):** a 1 ms clock.
//! - **CA2 (output):** the CVSD clock.
//! - **CB2 (output):** the CVSD data bit.
//!
//! Which means the speech is **bit-banged**: the CPU puts the bit on CB2 and
//! then pulses CA2, and the CVSD shifts it in on the rising edge.

use crate::levels;
use vpw_audio::{Cvsd, Dac};
use vpw_m6800::{Bus, Cpu};
use vpw_pia6821::Pia;

/// Clock of the board's 6808 (`wmssnd.c:497`).
pub const SOUND_CPU_CLOCK_HZ: u32 = 1_000_000;

/// How many cycles between toggles of the 1 ms clock that comes in on CB1.
const MILLISECOND_CYCLES: u64 = SOUND_CPU_CLOCK_HZ as u64 / 1000 / 2;

const RAM_SIZE: usize = 0x1000;
/// The two 32 KB images, one behind the other.
const ROM_REGION_SIZE: usize = 0x1_0000;
const BANK_SELECT: u16 = 0x1000;
const PIA_BASE: u16 = 0x2000;

/// The sound board's bus.
pub struct SoundBus {
    ram: Box<[u8; RAM_SIZE]>,
    /// `u21` at `$0000` and `u22` at `$8000`, the way `S11XS_SOUNDROM88`
    /// (`wmssnd.h:144`) loads them.
    rom: Box<[u8; ROM_REGION_SIZE]>,

    /// Offset within the region that the `$8000` window sees.
    low_window: usize,
    /// Offset that the `$C000` window sees.
    high_window: usize,

    pub pia: Pia,
    pub dac: Dac,
    pub cvsd: Cvsd,

    /// Previous level of CA2, to detect the edge that shifts the CVSD.
    last_cvsd_clock: bool,
    /// How many bits went into the CVSD since reset. Useful to tell "the table
    /// isn't talking" apart from "the speech path is broken".
    cvsd_bits: u64,
    /// How many times the DAC's level changed since reset.
    dac_writes: u64,

    /// Last access outside the map.
    pub last_unmapped: Option<u16>,
}

impl Default for SoundBus {
    fn default() -> Self {
        Self::new()
    }
}

impl SoundBus {
    pub fn new() -> Self {
        Self {
            ram: Box::new([0; RAM_SIZE]),
            rom: Box::new([0; ROM_REGION_SIZE]),
            // The banks boot-up leaves behind (`wmssnd.c:548`).
            low_window: 0xC000,
            high_window: 0x4000,
            pia: Pia::new(),
            dac: Dac::new(),
            cvsd: Cvsd::new(),
            last_cvsd_clock: false,
            cvsd_bits: 0,
            dac_writes: 0,
            last_unmapped: None,
        }
    }

    /// Loads the two 32 KB images: `u21` first, `u22` afterwards.
    pub fn load_roms(&mut self, u21: &[u8], u22: &[u8]) -> bool {
        if u21.len() != 0x8000 || u22.len() != 0x8000 {
            return false;
        }
        self.rom[0x0000..0x8000].copy_from_slice(u21);
        self.rom[0x8000..0x1_0000].copy_from_slice(u22);
        true
    }

    /// Write to `$1000`. Bit 0 picks the half of `u22` seen at `$8000` and bit
    /// 1 the half of `u21` seen at `$C000`.
    fn select_bank(&mut self, value: u8) {
        self.low_window = 0x8000 + (usize::from(value & 0x01) << 14);
        self.high_window = usize::from(value & 0x02) << 13;
    }

    /// What the main board left in the sound latch.
    pub fn set_sound_latch(&mut self, value: u8) {
        self.pia.set_port_a_input(value);
    }

    /// The handshake coming from CA2 of the main board's PIA 0.
    pub fn set_handshake(&mut self, level: bool) {
        self.pia.set_ca1(level);
    }

    /// Propagates to the audio chips whatever just went through the ports.
    ///
    /// It has to be called on PIA reads as well as writes, and not just by
    /// watching levels. F-14's ROM leaves CA2 in **pulse mode**: the CVSD's
    /// clock is not generated by the CPU moving a line, it is generated by the
    /// PIA itself, automatically, every time port A is **read**. It is a neat
    /// trick of the board —the same access that fetches the data generates the
    /// clock— and if one only watches levels on the writes, not a single bit
    /// shows up.
    fn service_audio(&mut self) {
        // Port B drives the DAC directly.
        let level = self.pia.port_b_output();
        if level != self.dac.level() {
            self.dac_writes += 1;
        }
        self.dac.write(level);

        // Pulse mode: the PIA exposes it as an event, because the pulse lasts
        // less than an instruction.
        if self.pia.take_ca2_pulse() {
            self.clock_cvsd();
        }

        // Manual or handshake mode: there CA2 does have a level, and the
        // rising edge is what counts.
        let clock = self.pia.ca2_output();
        if clock && !self.last_cvsd_clock {
            self.clock_cvsd();
        }
        self.last_cvsd_clock = clock;
    }

    fn clock_cvsd(&mut self) {
        let bit = self.pia.cb2_output();
        self.cvsd.clock(bit);
        self.cvsd_bits += 1;
    }

    /// Bits that went into the CVSD since reset.
    pub fn cvsd_bits(&self) -> u64 {
        self.cvsd_bits
    }

    /// DAC level changes since reset. It is the most direct sign that the
    /// board is producing audio and not merely running.
    pub fn dac_writes(&self) -> u64 {
        self.dac_writes
    }

    /// Audio sample from the board, with the effects and the speech at the
    /// levels the machine driver gives them. See [`crate::levels`].
    pub fn sample(&self) -> f32 {
        levels::weighted(&self.sources())
    }

    /// The board's sources with their levels, for a caller that has to mix them
    /// alongside another board's rather than after them. See
    /// [`crate::levels`] for why that distinction is not a detail.
    pub fn sources(&self) -> [(f32, f32); 2] {
        [
            (levels::DAC, self.dac.sample()),
            (levels::CVSD, self.cvsd.sample()),
        ]
    }
}

impl Bus for SoundBus {
    fn read(&mut self, addr: u16) -> u8 {
        match addr {
            0x0000..=0x0FFF => self.ram[addr as usize],
            0x2000..=0x2003 => {
                let value = self.pia.read((addr - PIA_BASE) as u8);
                // Reading port A is what pulses CA2, so the speech path goes
                // through here too.
                self.service_audio();
                value
            }
            0x8000..=0xBFFF => self.rom[self.low_window + (addr as usize - 0x8000)],
            0xC000..=0xFFFF => self.rom[self.high_window + (addr as usize - 0xC000)],
            _ => {
                self.last_unmapped = Some(addr);
                0xFF
            }
        }
    }

    fn write(&mut self, addr: u16, value: u8) {
        match addr {
            0x0000..=0x0FFF => self.ram[addr as usize] = value,
            BANK_SELECT => self.select_bank(value),
            0x2000..=0x2003 => {
                self.pia.write((addr - PIA_BASE) as u8, value);
                self.service_audio();
            }
            // Writing to the ROM does nothing.
            0x8000..=0xFFFF => {}
            _ => self.last_unmapped = Some(addr),
        }
    }
}

/// The complete sound board: CPU plus bus.
pub struct SoundBoard {
    pub cpu: Cpu,
    pub bus: SoundBus,
    cycle: u64,
    /// Cycle at which the 1 ms clock last toggled.
    last_millisecond_toggle: u64,
    millisecond_level: bool,
}

impl Default for SoundBoard {
    fn default() -> Self {
        Self::new()
    }
}

impl SoundBoard {
    pub fn new() -> Self {
        Self {
            cpu: Cpu::new(),
            bus: SoundBus::new(),
            cycle: 0,
            last_millisecond_toggle: 0,
            millisecond_level: false,
        }
    }

    /// Loads the two ROM images. Returns `false` if they are not 32 KB.
    pub fn load_roms(&mut self, u21: &[u8], u22: &[u8]) -> bool {
        self.bus.load_roms(u21, u22)
    }

    pub fn reset(&mut self) {
        self.bus.pia.reset();
        self.bus.dac.reset();
        self.bus.cvsd.reset();
        self.bus.cvsd_bits = 0;
        self.bus.dac_writes = 0;
        self.cycle = 0;
        self.last_millisecond_toggle = 0;
        self.millisecond_level = false;
        self.cpu.reset(&mut self.bus);
    }

    pub fn cycle(&self) -> u64 {
        self.cycle
    }

    /// Executes one instruction of the sound CPU.
    pub fn step(&mut self) -> u32 {
        // The board's PIA has its interrupt line wired to the IRQ of its own
        // 6808 (`wmssnd.c:574`).
        self.cpu.set_irq(self.bus.pia.irq());

        let cycles = self.cpu.step(&mut self.bus);
        self.cycle += u64::from(cycles);

        // The 1 ms clock comes in on CB1 and is what gives the sound routines
        // their time base.
        if self.cycle - self.last_millisecond_toggle >= MILLISECOND_CYCLES {
            self.millisecond_level = !self.millisecond_level;
            self.bus.pia.set_cb1(self.millisecond_level);
            self.last_millisecond_toggle = self.cycle;
        }

        cycles
    }

    /// Runs until reaching `target` cycles since reset.
    ///
    /// It is an **absolute** target, not an increment, and the difference
    /// matters: an instruction can overshoot the target by up to eleven cycles,
    /// and if one kept asking for "run N more cycles" every time, that overshoot
    /// would pile up. With the sound board that means running fast and putting
    /// all the audio out of tune.
    pub fn run_until(&mut self, target: u64) -> u64 {
        while self.cycle < target {
            self.step();
        }
        self.cycle
    }

    /// Runs at least `cycles` more cycles. For standalone use; inside a
    /// machine [`SoundBoard::run_until`] is the better one.
    pub fn run_cycles(&mut self, cycles: u64) -> u64 {
        self.run_until(self.cycle + cycles)
    }

    /// Sends it a sound number: leaves the latch and pulses the handshake.
    ///
    /// The pulse goes on CA1, which is what tells the board there is something
    /// new to read.
    pub fn send_command(&mut self, command: u8) {
        self.bus.set_sound_latch(command);
        self.bus.set_handshake(true);
        self.bus.set_handshake(false);
    }

    /// Current audio sample.
    pub fn sample(&self) -> f32 {
        self.bus.sample()
    }

    /// The board's sources with their levels. See [`crate::levels`].
    pub fn sources(&self) -> [(f32, f32); 2] {
        self.bus.sources()
    }
}
